/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CsRouteImport } from './routes/cs'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AtRiskRouteImport } from './routes/at-risk'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as TenantNameRouteImport } from './routes/tenant.$name'
import { Route as HelpScoreRouteImport } from './routes/help.score'
import { Route as HelpChangelogRouteImport } from './routes/help.changelog'
import { Route as CsTasksRouteImport } from './routes/cs.tasks'
import { Route as CsHistoryRouteImport } from './routes/cs.history'
import { Route as ApiPublicHooksGenerateWeeklyTasksRouteImport } from './routes/api/public/hooks/generate-weekly-tasks'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CsRoute = CsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskRoute = AtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const TenantNameRoute = TenantNameRouteImport.update({
  id: '/tenant/$name',
  path: '/tenant/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpScoreRoute = HelpScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => HelpRoute,
} as any)
const HelpChangelogRoute = HelpChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => HelpRoute,
} as any)
const CsTasksRoute = CsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CsRoute,
} as any)
const CsHistoryRoute = CsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CsRoute,
} as any)
const ApiPublicHooksGenerateWeeklyTasksRoute =
  ApiPublicHooksGenerateWeeklyTasksRouteImport.update({
    id: '/api/public/hooks/generate-weekly-tasks',
    path: '/api/public/hooks/generate-weekly-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/help/changelog': typeof HelpChangelogRoute
  '/help/score': typeof HelpScoreRoute
  '/tenant/$name': typeof TenantNameRoute
  '/help/': typeof HelpIndexRoute
  '/api/public/hooks/generate-weekly-tasks': typeof ApiPublicHooksGenerateWeeklyTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/help/changelog': typeof HelpChangelogRoute
  '/help/score': typeof HelpScoreRoute
  '/tenant/$name': typeof TenantNameRoute
  '/help': typeof HelpIndexRoute
  '/api/public/hooks/generate-weekly-tasks': typeof ApiPublicHooksGenerateWeeklyTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/help/changelog': typeof HelpChangelogRoute
  '/help/score': typeof HelpScoreRoute
  '/tenant/$name': typeof TenantNameRoute
  '/help/': typeof HelpIndexRoute
  '/api/public/hooks/generate-weekly-tasks': typeof ApiPublicHooksGenerateWeeklyTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/help'
    | '/login'
    | '/profile'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/help/changelog'
    | '/help/score'
    | '/tenant/$name'
    | '/help/'
    | '/api/public/hooks/generate-weekly-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/login'
    | '/profile'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/help/changelog'
    | '/help/score'
    | '/tenant/$name'
    | '/help'
    | '/api/public/hooks/generate-weekly-tasks'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/help'
    | '/login'
    | '/profile'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/help/changelog'
    | '/help/score'
    | '/tenant/$name'
    | '/help/'
    | '/api/public/hooks/generate-weekly-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AtRiskRoute: typeof AtRiskRoute
  ClubsRoute: typeof ClubsRoute
  CsRoute: typeof CsRouteWithChildren
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  UploadRoute: typeof UploadRoute
  TenantNameRoute: typeof TenantNameRoute
  ApiPublicHooksGenerateWeeklyTasksRoute: typeof ApiPublicHooksGenerateWeeklyTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs': {
      id: '/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof CsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk': {
      id: '/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof AtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/tenant/$name': {
      id: '/tenant/$name'
      path: '/tenant/$name'
      fullPath: '/tenant/$name'
      preLoaderRoute: typeof TenantNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/score': {
      id: '/help/score'
      path: '/score'
      fullPath: '/help/score'
      preLoaderRoute: typeof HelpScoreRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/changelog': {
      id: '/help/changelog'
      path: '/changelog'
      fullPath: '/help/changelog'
      preLoaderRoute: typeof HelpChangelogRouteImport
      parentRoute: typeof HelpRoute
    }
    '/cs/tasks': {
      id: '/cs/tasks'
      path: '/tasks'
      fullPath: '/cs/tasks'
      preLoaderRoute: typeof CsTasksRouteImport
      parentRoute: typeof CsRoute
    }
    '/cs/history': {
      id: '/cs/history'
      path: '/history'
      fullPath: '/cs/history'
      preLoaderRoute: typeof CsHistoryRouteImport
      parentRoute: typeof CsRoute
    }
    '/api/public/hooks/generate-weekly-tasks': {
      id: '/api/public/hooks/generate-weekly-tasks'
      path: '/api/public/hooks/generate-weekly-tasks'
      fullPath: '/api/public/hooks/generate-weekly-tasks'
      preLoaderRoute: typeof ApiPublicHooksGenerateWeeklyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CsRouteChildren {
  CsHistoryRoute: typeof CsHistoryRoute
  CsTasksRoute: typeof CsTasksRoute
}

const CsRouteChildren: CsRouteChildren = {
  CsHistoryRoute: CsHistoryRoute,
  CsTasksRoute: CsTasksRoute,
}

const CsRouteWithChildren = CsRoute._addFileChildren(CsRouteChildren)

interface HelpRouteChildren {
  HelpChangelogRoute: typeof HelpChangelogRoute
  HelpScoreRoute: typeof HelpScoreRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpChangelogRoute: HelpChangelogRoute,
  HelpScoreRoute: HelpScoreRoute,
  HelpIndexRoute: HelpIndexRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AtRiskRoute: AtRiskRoute,
  ClubsRoute: ClubsRoute,
  CsRoute: CsRouteWithChildren,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  UploadRoute: UploadRoute,
  TenantNameRoute: TenantNameRoute,
  ApiPublicHooksGenerateWeeklyTasksRoute:
    ApiPublicHooksGenerateWeeklyTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
