/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CsRouteImport } from './routes/cs'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AtRiskRouteImport } from './routes/at-risk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantNameRouteImport } from './routes/tenant.$name'
import { Route as CsTasksRouteImport } from './routes/cs.tasks'
import { Route as CsHistoryRouteImport } from './routes/cs.history'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CsRoute = CsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskRoute = AtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantNameRoute = TenantNameRouteImport.update({
  id: '/tenant/$name',
  path: '/tenant/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CsTasksRoute = CsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CsRoute,
} as any)
const CsHistoryRoute = CsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/tenant/$name': typeof TenantNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/tenant/$name': typeof TenantNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/clubs': typeof ClubsRoute
  '/cs': typeof CsRouteWithChildren
  '/upload': typeof UploadRoute
  '/cs/history': typeof CsHistoryRoute
  '/cs/tasks': typeof CsTasksRoute
  '/tenant/$name': typeof TenantNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/tenant/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/tenant/$name'
  id:
    | '__root__'
    | '/'
    | '/at-risk'
    | '/clubs'
    | '/cs'
    | '/upload'
    | '/cs/history'
    | '/cs/tasks'
    | '/tenant/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtRiskRoute: typeof AtRiskRoute
  ClubsRoute: typeof ClubsRoute
  CsRoute: typeof CsRouteWithChildren
  UploadRoute: typeof UploadRoute
  TenantNameRoute: typeof TenantNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs': {
      id: '/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof CsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk': {
      id: '/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof AtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/$name': {
      id: '/tenant/$name'
      path: '/tenant/$name'
      fullPath: '/tenant/$name'
      preLoaderRoute: typeof TenantNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cs/tasks': {
      id: '/cs/tasks'
      path: '/tasks'
      fullPath: '/cs/tasks'
      preLoaderRoute: typeof CsTasksRouteImport
      parentRoute: typeof CsRoute
    }
    '/cs/history': {
      id: '/cs/history'
      path: '/history'
      fullPath: '/cs/history'
      preLoaderRoute: typeof CsHistoryRouteImport
      parentRoute: typeof CsRoute
    }
  }
}

interface CsRouteChildren {
  CsHistoryRoute: typeof CsHistoryRoute
  CsTasksRoute: typeof CsTasksRoute
}

const CsRouteChildren: CsRouteChildren = {
  CsHistoryRoute: CsHistoryRoute,
  CsTasksRoute: CsTasksRoute,
}

const CsRouteWithChildren = CsRoute._addFileChildren(CsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtRiskRoute: AtRiskRoute,
  ClubsRoute: ClubsRoute,
  CsRoute: CsRouteWithChildren,
  UploadRoute: UploadRoute,
  TenantNameRoute: TenantNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
