// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { supabase as browserSupabase } from './client'

export const requireSupabaseAuth = createMiddleware({ type: 'function' })
  .client(async ({ next }) => {
    // Forward the current user's access token from the browser session to the server.
    let headers: HeadersInit = {}
    try {
      const { data } = await browserSupabase.auth.getSession()
      const token = data.session?.access_token
      if (token) {
        headers = { Authorization: `Bearer ${token}` }
      }
    } catch {
      // best effort — server will reject if no token
    }
    return next({ headers })
  })
  .server(async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.',
        { status: 500 },
      )
    }

    const request = getRequest()
    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 })
    }

    const authHeader = request.headers.get('authorization')
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Missing bearer token', { status: 401 })
    }
    const token = authHeader.replace('Bearer ', '').trim()
    if (!token) {
      throw new Response('Unauthorized: Empty token', { status: 401 })
    }

    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${token}` } },
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    })

    const { data, error } = await supabase.auth.getClaims(token)
    if (error || !data?.claims) {
      throw new Response('Unauthorized: Invalid token', { status: 401 })
    }
    if (!data.claims.sub) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 })
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub as string,
        claims: data.claims,
      },
    })
  })
